# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'StanwoodiOSAssignment' do
  pod 'Alamofire'
  use_frameworks!

  # Pods for StanwoodiOSAssignment

  target 'StanwoodiOSAssignmentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StanwoodiOSAssignmentUITests' do
    # Pods for testing
  end

end
