# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'StanwoodiOSAssignment' do
  pod 'Alamofire'
  pod 'RealmSwift'
  pod 'Kingfisher'
  use_frameworks!

  # Pods for StanwoodiOSAssignment

  target 'StanwoodiOSAssignmentTests' do
    inherit! :search_paths
    # Pods for testing
  pod 'RealmSwift'
  end

  target 'StanwoodiOSAssignmentUITests' do
    # Pods for testing
  pod 'RealmSwift'
  end

post_install do |installer|
     installer.pods_project.targets.each do |target|
           target.build_configurations.each do |config|
                 config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
           end
     end
 end
end
